name = "All the Mods 9 - To the Sky - atm9sky"
author = "ATM Team"
version = "1.1.7b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6b903edf2619351ceaf49c1dd943f5249c882b2fd3fc186db9c754c753158be"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
